
name: Run npm Test

on: 
  push:
  pull_request:
    types: open

jobs:
  build:
        runs-on: ubuntu-latest

        steps: 

        - uses: actions/checkout@v4.1.1
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.0.0
          with:
            node-version: 18.x
            
        - run: npm ci
        - run: npm run build --if-persent
        - run: npm run test -- --coverage
      
